### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by amivaleo** [Rafostar/gnome-shell-extension-cast-to-tv#1]
Hi!
I'd like to translate this into Italian.
Can you add locale folder, pot file, etc? :)

**Comment by Rafostar** [comment]
As requested, I have added `po` directory with `.pot` file.
Please use `Makefile` for updating `.pot` and generating `.mo` files as described [in readme](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv#for-translators).
After translating, send back **only** `.po` file with translations (it can be in pull request).
I will be syncing line numbers and generating `.mo` before each new release.

**Comment by amivaleo** [comment]
Thank you. :)
Give me some time, I don't have my computer with me.

**Comment by Rafostar** [comment]
Of course. There is no need to rush. I am still working on improving main code.

**Comment by Rafostar** [comment]
Translations added. Closes #2

**Comment by fabrixx** [comment]
Hi. I'm italian, I finded Italian translation inside (po folder) but addon still in english.
I've to recompile to apply it?

Thanks

**Comment by Rafostar** [comment]
1. Download v5 from releases page (current git is unstable)
2. Extract it
3. Open terminal inside and execute `make install`
4. `Alt+F2`, `r`, `Enter` (or reboot)

Remember to manually install npm dependencies (only if you have not done it already).

**Comment by Rafostar** [comment]
Just to clarify for future visitors. The only reason we had to manually install latest release from git is because this translation was added in versions 3 and up. Current version on official gnome extensions website is v2 (due to slow review process). As soon as new version will be available on that website you can simply install it with one button toggle and have translations out of the box.
