### ISSUE TITLE
[Feature Request] Volume control

### ISSUE THREAD

**Issue by djerius** [Rafostar/gnome-shell-extension-cast-to-tv#18]
It would be great if one could adjust the volume from within the top bar remote.

Thanks for a great application!

**Comment by Rafostar** [comment]
Volume control function should not be a problem (and I wanted to add it some time ago), but the actual problem is where to put it on the remote widget to not make it look ugly.

<img src=/Rafostar/gnome-shell-extension-cast-to-tv/wiki/images/Remote.png>

I can make it as a second slider, but wouldn't it make it misleading? (user adjust wrong slider by mistake)
It can also be in form of +/- buttons with volume % text, but I do not know where to put them to not break the overall good look/simplicity.

How about changing icon next to silder into a toggle button that switches progress slider into a volume slider? (the best I could think of)

I am open to all users suggestions.

**Comment by djerius** [comment]
How about something like this?

![Screenshot from 2019-04-08 19-13-17](https://user-images.githubusercontent.com/196875/55762834-750a8880-5a32-11e9-8aba-ef3eb79a1998.png)

**Comment by Rafostar** [comment]
Volume slider is something that most users might not change more than once per video. So I kinda favour option with toggle button, but yours make it more accessible. When I have time I will try to add both approaches and a settings menu option to choose between them. That should satisfy everyone.

**Comment by djerius** [comment]
> Volume slider is something that most users might not change more than once per video. 

That's a good point. 

Thanks again for your efforts.

**Comment by Rafostar** [comment]
Added volume control core functionality. Since next extension version will allow controlling web browser playback from GNOME Shell, the slider will be useful for other devices too :smile: 

Let's not close this issue yet. Option for extension settings to allow users choose if they want to see both sliders at once still needs to be added.

**Comment by djerius** [comment]
Thanks again!
