### ISSUE TITLE
Playing over VPN

### ISSUE THREAD

**Issue by RobertZito** [Rafostar/gnome-shell-extension-cast-to-tv#3]
What ports do I need to open to cast while VPN is on, when I shut it off all works fine. Also does not show option to stream Pictures.

**Comment by Rafostar** [comment]
Chromecast was never intended to play over internet or using different subnets. When devices are connected to the same network, usually communication on all ports between them is allowed. I was not doing 'castv2' and 'chromecast-scanner' implementations in node, so I do not know the details how exactly connection is established. Port set in extension is the port to serve the content. There are more details on other ports used [here](https://blog.g3rt.nl/allow-google-chromecast-host-firewall-iptables.html).

The extension on gnome extensions website is currently v2 (new versions are pending review). Casting pictures was introduced in v3. Changes are described on the [releases page](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/releases).

**Comment by Rafostar** [comment]
The extension description clearly says **over local network**. Your description is unclear. Playing **over VPN** and playing **while VPN is on** are two totally different issues. You named this issue as playing over VPN, so I will treat it as such. I am closing this as it is unrelated, because you are not using local home network.
