### ISSUE TITLE
Increased CPU usage with Cast to TV

### ISSUE THREAD

**Issue by rmeissn** [Rafostar/gnome-shell-extension-cast-to-tv#32]
I'm using Cast to TV from extensions.gnome.org (followed the setup instructions of this repo).
Some time later I wondered why my laptops fan was busy all the time. The system monitor showed a cpu usage of 10-35% of one core, caused by gnome-shell. By disabling the Cast to TV extensions the cpu usage of gnome-shell dropped immediately to 0.
I noticed this issue in the eduroam wifi network and guess the extensions is trying to search for cast receivers and won't stop searching after some time. But that's just a guess.
I'll happily contribute logs if someone tells me which ones are needed.

**Comment by Rafostar** [comment]
> By disabling the Cast to TV extensions the cpu usage of gnome-shell dropped immediately to 0.

OK, but try disabling all other extensions except Cast to TV and see if problem still exists (make sure this is not caused by other extension conflicting with this one).

And secondly, this extension comes in two parts (extension + node service). If your problem still exists, let's try to stop the spawned service to find out if the problem is not actually caused by it (the easiest way is to run `sudo killall node`) and then check if cpu usage drops.

**Comment by rmeissn** [comment]
It seems like it is caused by another extensions, see https://github.com/phocean/TopIcons-plus/issues/118
I guess disabling CastToTV had the same effect like the recommended option to change the alignment, thus the CPU usage dropped but the initial issue is not caused by CastToTV. Sorry for not properly investigating before posting this issue.

**Comment by Rafostar** [comment]
No problem. Glad everything works now.
