### ISSUE TITLE
Node server doesn't auto-start and no cast option in Nautilus

### ISSUE THREAD

**Issue by dandarie** [Rafostar/gnome-shell-extension-cast-to-tv#34]
Hi.

I have installed the extension from source using the instructions from the Wiki. Paths are OK, node modules were installed, the extension is enabled, I can see its icon in the tray. The config points to the right Chromecast device; also, the issue persists with browser players.

When I try to cast a file, nothing happens. Everything works as expected only after I manually start the node server with `nodejs node_scripts/server.js`.

Also, after installing the required packages, the Nautilus integration doesn't seem to work.

I'm using Cast to TV - Gnome Shell Extension v9.
The node version is v10.15.2.

**Comment by Rafostar** [comment]
Try solving it with steps from [here](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/wiki/Installation#install-extension) (below break line).

**Comment by dandarie** [comment]
I literally mentioned I have installed the extension using the instructions fron the Wiki that at the beginning of the issue.

I also mentioned the extrension loads, but it doesn't start the server. I've checked, it's not loaded. I have restarted gnome-shell, and even the computer, with the same result: the extension loads, the server doesn't start.

Only after I start the server manually does the extension cast.

**Comment by Rafostar** [comment]
> I literally mentioned I have installed the extension using the instructions fron the Wiki that at the beginning of the issue.

Yes, and I understood that. Sorry if it wasn't clear. You said that server can be manually started with:
`nodejs node_scripts/server.js`, so I assumed that you did not create symlink from `nodejs` to `node`. Currently executable name `node` is hardcoded in extension and that last step in installation (after break line) does not apply to everyone.

Basically what I am asking you is:
Can you launch it manually like you did but with `node` instead of `nodejs`?

And if answer is 'Yes', try starting server monitoring app in terminal within extension folder manually (this is the extension part responsible for starting node server):
```
pkill -f cast-to-tv
gjs server-monitor.js
```

And see if it launches node server correctly and does not output any errors to the terminal while running.

**Comment by dandarie** [comment]
> Can you launch it manually like you did but with node instead of nodejs?

It works with node, either. Sorry, I forgot to mention that earlier. The symlink was created during install. It's an Ubuntu 19.04 box, by the way. Maybe that helps. 

```
$ ls -l `which nodejs`
lrwxrwxrwx 1 root root 24 mai 15 19:58 /usr/bin/nodejs -> /etc/alternatives/nodejs

$ ls -l /etc/alternatives/nodejs
lrwxrwxrwx 1 root root 13 mai 15 19:58 /etc/alternatives/nodejs -> /usr/bin/node
```

The monitor starts just fine.

```
$ gjs server-monitor.js
Started Cast to TV service
```

I have no clue about how GNOME extensions work, but maybe something happens in extension,js, in the enable function, before the monitor is supposed to start. Is there a way I can test or see a debug output of that?

**Comment by Rafostar** [comment]
This extension spawns server-monitor as separate process exactly the same way as you did (to not leave a zombie process when gnome-shell restarts). So why it works manually from terminal and why not from extension for you remains a mystery. Perhaps we can find some info in:
```
journalctl --since yesterday | grep -i cast
```
Also I doubt it is different in your distro, but what is `which gjs` path result?

**Comment by Rafostar** [comment]
Closed due to inactivity
