### ISSUE TITLE
Automatic image slideshow [feature request]

### ISSUE THREAD

**Issue by logix2** [Rafostar/gnome-shell-extension-cast-to-tv#84]
If possible, please implement the ability to automatically play multiple images (maybe with a configurable delay between images), without having to click the "Next" button on the desktop to advance to the next image.

**Comment by Rafostar** [comment]
Hi @logix2 
That is a nice feature. I will definitely add it, but right now I need to make a new release with currently added new features (especially "Drag and Drop" support in playlist that making was giving me a headache) and GNOME 3.34 support as next Ubuntu/Fedora releases are upon us. Due to this I need to be careful to not break anything in code right now.

BTW: Thanks for still using my extension and writing those articles on linuxuprising.

**Comment by Rafostar** [comment]
@logix2 
As you requested, I added the slideshow functionality to the extension. Time per picture can be set in extension preferences (remote tab). Slideshow can be toggled on/off with an added to the widget camera button. I also made the repeat button work with it, cause I thought it might be useful to be able to put the images on the loop instead of closing cast after last image.

**Comment by logix2** [comment]
Thank you, much appreciated!
