### ISSUE TITLE
[Feature] Let me select chromecast device every time

### ISSUE THREAD

**Issue by snaggen** [Rafostar/gnome-shell-extension-cast-to-tv#88]
Currently I have to either select a fixed chromecast or have an Automatic setting, but I have 3 Chromecasts and 3 Chromecast Audio so the Automatic selection will never guess the right one. This means that I almost all the time have to go in to the settings, select the correct tab and then select the correct device. This is quite a few clicks.
I think the default should be to "Always Ask" that presents a list of available devices, with a possible "remember my choice" checkbox.

**Comment by Rafostar** [comment]
How would "remember my choice" be any different to what is available now?

This suggestion is convenient for people that have multiple devices and constantly change their destination device, but on the other hand this introduces additional clicks for those with only one device or the ones that keep casting to the same one from PC (they would need to select it each time from the list).

I agree that current behaviour can be simplified for people with multiple devices, but only if they want it to. My proposal here is to add an additional option to device selection in extension preferences besides "Automatic" and fixed names. Something like "On file select", then the extension will present you a devices list during file selection each time. How about it?

**Comment by snaggen** [comment]
The "Remember my choice" would be exactly what is available today, since I assume that works for some people (while other people like me need "Always Ask" behaviour). So defaulting to asking, with the option to remember the choice would have a good balance between discoverability and usability. 
But just adding a option "Always Ask" (or "On file select", but always ask is a more common phrasing in other apps, but I'm no UI expert) in the settings, for people like me would solve my issue.

**Comment by Rafostar** [comment]
"Always Ask" is the usual way. I just took into consideration that with this option, Nautilus extension needs to be modified to show device list in Nautilus right click menu and select "Your Device Name" -> "Cast Selected File". There is no question then (just device selection).

**Comment by Rafostar** [comment]
@snaggen 
Done! In the end I simply added device selection at the bottom of file chooser. This should be the fastest way to change destination device without complicating things (no additional popups and dialogs). It will also automatically remember last selected device (even across reboots). Nautilus extension changes involved more work. A submenu with devices will be available only if scanned devices list is greater than one (again this should be the most efficient behaviour to both people with one or multiple devices). Because app allows only casting to one device at a time, the selection will appear only when cast is stopped, otherwise it will show standard "Add to Playlist" option.

If you want to try it now (before next release) you can `make install` from latest git master (no need to remove current installation as files will be replaced with new ones).

**Comment by snaggen** [comment]
The selection seems to work fine, and that solution solves my situation perfectly! Great job. 
However, the actual casting didn't work for me. Initially my previous list of devices was remembered from my previous install, but when it tried to cast it failed to find the devices. Then when I tried to scan for devices, it didn't find anything. I have tried to remove the directory and reinstall the plugin and modules, logout and back in just to ensure no old stuff war kept in memory. So, I have some issues with master... probably not related to this, but thought you might want to know.

**Comment by snaggen** [comment]
Ok, the issue I had was related to my network. When that was fixed, everything worked fine. Thanks for a fast response!

**Comment by Rafostar** [comment]
OK. Glad it works as I have not done any scanning changes between last release and current git master.

To tell the truth I only have one Chromecast, so if you encounter any problems with my recent implementation of device selection let me know. For now I consider this solved. Closing.
